# Generated by Django 3.1.1 on 2020-09-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Номер телефона')),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=1, verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('email_is_verified', models.BooleanField(default=False, verbose_name='Подтверждена почта')),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ['phone_number'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
