GET = "GET"
POST = "POST"
ONLY_GET = [GET]
ONLY_POST = [POST]
GET_AND_POST = [GET, POST]

SIGN_UP_PAGE = "SIGN_UP_PAGE"
SIGN_UP_PAGE_FIRST = "1"
SIGN_UP_PAGE_SECOND = "2"
SIGN_UP_PAGE_THIRD = "3"
SIGN_UP_PAGE_FOURTH = "4"
SIGN_UP_PAGE_FIFTH = "5"
SIGN_UP_PAGE_COOKIE_AGE = 120  # cookie lives in secs
SIGN_UP_COOKIE_FIRST_NAME = "SIGN_UP_COOKIE_FIRST_NAME"
SIGN_UP_COOKIE_LAST_NAME = "SIGN_UP_COOKIE_LAST_NAME"
SIGN_UP_COOKIE_DAY = "SIGN_UP_COOKIE_DAY"
SIGN_UP_COOKIE_MONTH = "SIGN_UP_COOKIE_MONTH"
SIGN_UP_COOKIE_YEAR = "SIGN_UP_COOKIE_YEAR"
SIGN_UP_COOKIE_GENDER = "SIGN_UP_COOKIE_GENDER"
SIGN_UP_COOKIE_PHONE_NUMBER = "SIGN_UP_COOKIE_PHONE_NUMBER"
SIGN_UP_COOKIE_PHONE_NUMBER_CODE = "SIGN_UP_COOKIE_PHONE_NUMBER_CODE"
SIGN_UP_COOKIE_ERROR = "SIGN_UP_COOKIE_ERROR"

LOGIN_COOKIE_ERROR = "LOGIN_COOKIE_ERROR"
SETTINGS_COOKIE_EMAIL_VERIFIED = "SETTINGS_COOKIE_EMAIL_VERIFIED"
CALORIES_COOKIE_DATA_VALID = "CALORIES_COOKIE_DATA_VALID"

NONE = ""
IS_OK = "True"
IS_NOT_OK = "False"

ERROR = "error"
FORM = "form"
ITEMS = "items"
CLEAR = "clear"
FIND = "find"

TITLE = "title"
TITLE_EN = "title_en"
KCAL = "kcal"
PROTEIN = "protein"
OIL = "oil"
CARB = "carb"

KCAL_FROM = "kcal_from"
KCAL_TO = "kcal_to"
PROTEIN_FROM = "protein_from"
PROTEIN_TO = "protein_to"
OIL_FROM = "oil_from"
OIL_TO = "oil_to"
CARB_FROM = "carb_from"
CARB_TO = "carb_to"

CALORIES_FIND_TEMPLATE = "{}-{}-{}-{}-{}-{}-{}-{}-{}"

MIN_CALORIES_VALUE = 0
MAX_CALORIES_VALUE = 1000000

LANGUAGE_RU = "ru"
LANGUAGE_EN = "en"

ANY_TITLE = ""

DATA = "data"
ATHLETE = "athlete"

RUN_60 = "run_60"
RUN_100 = "run_100"
RUN_3000 = "run_3000"
CHIN_UPS = "chin_ups"
PUSH_UPS = "push_ups"
SIT_UPS = "sit_ups"
SQUAT = "squat"
BENCH_PRESS = "bench_press"
DEAD_LIFT = "dead_lift"

GENDER = "gender"
EMAIL_MESSAGE = "email_message"
EMAIL_MESSAGE_VERIFIED = "email_message_verified"
RATING_DATA = "rating_data"
SPORTSMAN_DATA = "sportsman_data"
USER_DATA = "user_data"

HTTP_REFERER = "HTTP_REFERER"
DJANGO_LANGUAGE = "django_language"

EXCEPTION = "exception"

PHONE_NUMBER = "phone_number"
PASSWORD = "password"
CODE_FOR_PHONE_NUMBER = "code_for_phone_number"
STAGE = "stage"
SUBMIT_VALUE = "submit_value"
FIRST_NAME = "first_name"
LAST_NAME = "last_name"
DAY = "day"
MONTH = "month"
YEAR = "year"
EMAIL = "email"
AVATAR = "avatar"

TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_SERVICE_TOKEN = "TWILIO_SERVICE_TOKEN"

MALE = "Male"
FEMALE = "Female"

DEBUG_TRUE = "1"
DEBUG_FALSE = "0"
DEBUG_VALUE = "DEBUG"
SECRET_KEY_VALUE = "SECRET_KEY"
AWS_ACCESS_KEY_ID_VALUE = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_VALUE = "AWS_SECRET_ACCESS_KEY"
AWS_STORAGE_BUCKET_NAME_VALUE = "S3_BUCKET_NAME"
EMAIL_HOST_USER_VALUE = "EMAIL_HOST_USER"
EMAIL_HOST_PASSWORD_VALUE = "EMAIL_HOST_PASSWORD"
CELERY_BROKER_URL_VALUE = "REDIS_URL"
CELERY_RESULT_BACKEND_VALUE = "REDIS_URL"

LANGUAGE_CODE_VALUE = "LANGUAGE_CODE"

COUNTRY_REGION = "country_region"
