version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 30429:30429
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/mytruegym/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery worker -A mytruegym -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: