# Generated by Django 3.1.1 on 2020-09-21 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_60', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Бег на 60 м')),
                ('run_100', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Бег на 100 м')),
                ('run_3000', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Бег на 3000 м')),
                ('chin_ups', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Подтягивания')),
                ('push_ups', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Отжимания')),
                ('sit_ups', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Приседания')),
                ('squat', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Приседания со штангой')),
                ('bench_press', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Жим лежа со штангой')),
                ('dead_lift', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Тяга штанги от пола')),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Атлет')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['run_60'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
